name: Deploy docs

on:
  push:
    branches: ["main", "develop"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    env:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: Generate Docs
        run: |
          cargo doc --no-deps
          rm -rf ./docs
          echo "<meta http-equiv=\"refresh\" content=\"0; url=cli_config\" />" > target/doc/index.html
          cp -rf ./target/doc ./docs
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./docs"
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
